package com.ptit.rms.model;
// Generated Aug 7, 2017 10:58:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtmenuId generated by hbm2java
 */
@Embeddable
public class CtmenuId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idmenu;
	private int idmonAn;

	public CtmenuId() {
	}

	public CtmenuId(int idmenu, int idmonAn) {
		this.idmenu = idmenu;
		this.idmonAn = idmonAn;
	}

	@Column(name = "IDMenu", nullable = false)
	public int getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(int idmenu) {
		this.idmenu = idmenu;
	}

	@Column(name = "IDMonAn", nullable = false)
	public int getIdmonAn() {
		return this.idmonAn;
	}

	public void setIdmonAn(int idmonAn) {
		this.idmonAn = idmonAn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtmenuId))
			return false;
		CtmenuId castOther = (CtmenuId) other;

		return (this.getIdmenu() == castOther.getIdmenu()) && (this.getIdmonAn() == castOther.getIdmonAn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdmenu();
		result = 37 * result + this.getIdmonAn();
		return result;
	}

}
