package com.ptit.rms.model;
// Generated Aug 7, 2017 10:58:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ctmenu generated by hbm2java
 */
@Entity
@Table(name = "CTMenu")
public class Ctmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CtmenuId id;
	private Menu menu;
	private MonAn monAn;
	private int soluong;

	public Ctmenu() {
	}

	public Ctmenu(CtmenuId id, Menu menu, MonAn monAn, int soluong) {
		this.id = id;
		this.menu = menu;
		this.monAn = monAn;
		this.soluong = soluong;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idmenu", column = @Column(name = "IDMenu", nullable = false)),
			@AttributeOverride(name = "idmonAn", column = @Column(name = "IDMonAn", nullable = false)) })
	public CtmenuId getId() {
		return this.id;
	}

	public void setId(CtmenuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDMenu", nullable = false, insertable = false, updatable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDMonAn", nullable = false, insertable = false, updatable = false)
	public MonAn getMonAn() {
		return this.monAn;
	}

	public void setMonAn(MonAn monAn) {
		this.monAn = monAn;
	}

	@Column(name = "soluong", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

}
