package com.ptit.rms.model;
// Generated Jul 11, 2017 9:20:47 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoryTracking generated by hbm2java
 */
@Entity
@Table(name = "history_tracking", catalog = "course")
public class HistoryTracking {

  private int historyId;
  private Items items;
  private String value;
  private Date createdAt;
  private Date updatedAt;
  private int createdBy;
  private int updatedBy;

  public HistoryTracking() {
  }

  public HistoryTracking(int historyId, Items items, String value, Date createdAt, Date updatedAt, int createdBy,
      int updatedBy) {
    this.historyId = historyId;
    this.items = items;
    this.value = value;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.createdBy = createdBy;
    this.updatedBy = updatedBy;
  }

  @Id

  @Column(name = "history_id", unique = true, nullable = false)
  public int getHistoryId() {
    return this.historyId;
  }

  public void setHistoryId(int historyId) {
    this.historyId = historyId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "item_id", nullable = false)
  public Items getItems() {
    return this.items;
  }

  public void setItems(Items items) {
    this.items = items;
  }

  @Column(name = "value", nullable = false)
  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created_at", nullable = false, length = 23)
  public Date getCreatedAt() {
    return this.createdAt;
  }

  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updated_at", nullable = false, length = 23)
  public Date getUpdatedAt() {
    return this.updatedAt;
  }

  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  @Column(name = "created_by", nullable = false)
  public int getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(int createdBy) {
    this.createdBy = createdBy;
  }

  @Column(name = "updated_by", nullable = false)
  public int getUpdatedBy() {
    return this.updatedBy;
  }

  public void setUpdatedBy(int updatedBy) {
    this.updatedBy = updatedBy;
  }

}
