package com.ptit.rms.model;
// Generated Jul 11, 2017 9:20:47 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemData generated by hbm2java
 */
@Entity
@Table(name = "item_data")
public class ItemData {

  private int itemDataId;
  private AuditDate auditDate;
  private Items items;
  private String value;
  private String imageUrl;
  private Date createdAt;
  private Date updatedAt;
  private int createdBy;
  private int updatedBy;

  public ItemData() {
  }

  public ItemData(int itemDataId, AuditDate auditDate, Items items, String value, Date createdAt, Date updatedAt, int createdBy, int updatedBy) {
    this.itemDataId = itemDataId;
    this.auditDate = auditDate;
    this.items = items;
    this.value = value;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.createdBy = createdBy;
    this.updatedBy = updatedBy;
  }

  public ItemData(int itemDataId, AuditDate auditDate, Items items, String value, String imageUrl, Date createdAt, Date updatedAt, int createdBy,
      int updatedBy) {
    this.itemDataId = itemDataId;
    this.auditDate = auditDate;
    this.items = items;
    this.value = value;
    this.imageUrl = imageUrl;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.createdBy = createdBy;
    this.updatedBy = updatedBy;
  }

  @Id

  @Column(name = "uid", unique = true, nullable = false)
  public int getItemDataId() {
    return this.itemDataId;
  }

  public void setItemDataId(int itemDataId) {
    this.itemDataId = itemDataId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "audit_date_id", nullable = false)
  public AuditDate getAuditDate() {
    return this.auditDate;
  }

  public void setAuditDate(AuditDate auditDate) {
    this.auditDate = auditDate;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "item_id", nullable = false)
  public Items getItems() {
    return this.items;
  }

  public void setItems(Items items) {
    this.items = items;
  }

  @Column(name = "value", nullable = false)
  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  @Column(name = "image_url")
  public String getImageUrl() {
    return this.imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created_at", nullable = false, length = 23)
  public Date getCreatedAt() {
    return this.createdAt;
  }

  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updated_at", nullable = false, length = 23)
  public Date getUpdatedAt() {
    return this.updatedAt;
  }

  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  @Column(name = "created_by", nullable = false)
  public int getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(int createdBy) {
    this.createdBy = createdBy;
  }

  @Column(name = "updated_by", nullable = false)
  public int getUpdatedBy() {
    return this.updatedBy;
  }

  public void setUpdatedBy(int updatedBy) {
    this.updatedBy = updatedBy;
  }

}
