package com.ptit.rms.model;
// Generated Aug 7, 2017 10:58:33 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "Menu")
public class Menu{

	private int idmenu;
	private String tenMenu;
	private Set<DatBan> datBans = new HashSet<DatBan>(0);
	private Set<Ctmenu> ctmenus = new HashSet<Ctmenu>(0);

	public Menu() {
	}

	public Menu(int idmenu, String tenMenu) {
		this.idmenu = idmenu;
		this.tenMenu = tenMenu;
	}

	public Menu(int idmenu, String tenMenu, Set<DatBan> datBans, Set<Ctmenu> ctmenus) {
		this.idmenu = idmenu;
		this.tenMenu = tenMenu;
		this.datBans = datBans;
		this.ctmenus = ctmenus;
	}

	@Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IDMenu", unique = true, nullable = false)
	public int getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(int idmenu) {
		this.idmenu = idmenu;
	}

	@Column(name = "TenMenu", nullable = false)
	public String getTenMenu() {
		return this.tenMenu;
	}

	public void setTenMenu(String tenMenu) {
		this.tenMenu = tenMenu;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<DatBan> getDatBans() {
		return this.datBans;
	}

	public void setDatBans(Set<DatBan> datBans) {
		this.datBans = datBans;
	}
	
  @JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "menu")
	public Set<Ctmenu> getCtmenus() {
		return this.ctmenus;
	}

	public void setCtmenus(Set<Ctmenu> ctmenus) {
		this.ctmenus = ctmenus;
	}

}
